### ISSUE TITLE
Increasing the hang threshold seems to never increment

### ISSUE THREAD

**Issue by chutten** [chutten/statuser#20]
If you increase the hang threshold number, statuser seems to never count a background hang (as reported by :avih) even when one shows up in about:telemetry in the 255 bucket, or one is forced by running a tight loop in the parent process.

**Comment by Uberi** [comment]
In IRC, :avih mentioned that this actually seems to be more of a "delay", so the counter only increments once the hanging is over.

I'm not sure there's anything we can do about this.

**Comment by chutten** [comment]
RESOLVED WORKSFORME

**Comment by avih** [comment]
> In IRC, :avih mentioned that this actually seems to be more of a "delay", so the counter only increments once the hanging is over.

Despite me not being able to reproduce it at some stage, I think this issue was still around and intermittent up to and including version 0.1.13.

It seems that 0.1.14 finally fixed it properly as a by product of some refactoring - the stated changelog for 0.1.14 includes only better text to describe the actual threshold used, but as far as I can tell it also fixed/improved the issue of this bug (tested both nightly and aurora).
